---
- name: Render Prometheus configuration on host
  delegate_to: localhost
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /tmp/althea-prometheus-{{ inventory_hostname }}.yml
    mode: '0644'

- name: Copy Prometheus config into container
  delegate_to: localhost
  community.docker.docker_container_copy_into:
    container: "{{ inventory_hostname }}"
    path: /tmp/althea-prometheus-{{ inventory_hostname }}.yml
    container_path: /etc/prometheus/prometheus.yml

- name: Restart Prometheus to load new config
  delegate_to: localhost
  community.docker.docker_container:
    name: "{{ inventory_hostname }}"
    state: started
    restart: true

- name: Cleanup temp file
  delegate_to: localhost
  ansible.builtin.file:
    path: /tmp/althea-prometheus-{{ inventory_hostname }}.yml
    state: absent
